/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pl_pilotto_server_service_media_WindowsMediaKeysService */

#ifndef _Included_pl_pilotto_server_service_media_WindowsMediaKeysService
#define _Included_pl_pilotto_server_service_media_WindowsMediaKeysService
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pl_pilotto_server_service_media_WindowsMediaKeysService
 * Method:    playPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pl_pilotto_server_service_media_WindowsMediaKeysService_playPause
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
